# Generated by Django 3.2.8 on 2021-10-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaDuodigito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.BigIntegerField(default=0)),
                ('multiplo_duodigito', models.BigIntegerField(default=0, editable=False)),
                ('tempo_duodigito', models.IntegerField(default=1.9500000000061135e-05)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
