# Generated by Django 3.2.8 on 2021-10-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaduodigito',
            name='tempo_duodigito',
            field=models.IntegerField(default=1.6600000000033255e-05),
        ),
    ]
