# Generated by Django 3.2.8 on 2021-10-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_entradaduodigito_tempo_duodigito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaduodigito',
            name='tempo_duodigito',
            field=models.IntegerField(default=1.6200000000021753e-05),
        ),
    ]
